### ISSUE TITLE
Selecting Class in Polygon batch overlay crashes QGis in Ubuntu

### ISSUE THREAD

**Issue by kdarras** [Martin-Jung/LecoS#10]
Steps to reproduce:

Open Qgis
import polygons (in my case, circles created from a fixed distance buffer based on points)
import a raster (in my case, land cover raster, of the same projection)
install LeCos (I have the latest version)
Select Landscape Vector overlay
Select class

The screen first freezes and then crashes.

Using Lecos latest version, Qgis 2.18.16, Ubuntu 16.04 LTS.

Issue does not happen on Windows using exact same project file with up-to date QGis and Lecos plugin.

**Comment by Martin-Jung** [comment]
Thanks for reporting.
Unsure about the cause and will investigate when possible. Would be excellent if you could provide a small test subset of your raster / polygon file. 
Can you get me the version numbers of your numpy/scipy/pil libraries on Linux ?

**Comment by kdarras** [comment]
Hi Martin,
sorry I was struggling with clipping my raster file, and it still gives me errors, so here is another freely available raster:
http://download.osgeo.org/geotiff/samples/gdal_eg/

After importing that, I create a new polygon shapefile, add a new feature (a triangle), and open up the landscape ecology tool: Landscape vector overlay.
I select both files to overlay, and when I switch from the default radio button "landscape" to "Class", QGIS just crashes.

I cannot find my numpy/scipy/pil libraries versions, any hint? I tried different solutions from StackOverflow but none worked.

**Comment by Martin-Jung** [comment]
You can query the version of your numpy/scipy/pil libraries via the QGIS python console:
Menu Plugins -> Python Console:

Type:
```
import scipy
scipy.__version__
```
For PIL
```
import PIL
PIL.VERSION
```

**Comment by kdarras** [comment]
Thanks!
Scipy: 0.17.0
PIL: 1.1.7
numpy: 1.11.0

**Comment by Martin-Jung** [comment]
Okay. Tested it out and mine is working just fine (see screenshot). There must be something weird with your Linux system setup, although we have the same system setup (Ubuntu 16.04, scipy:0.17, PIL, 1.1.7).
Often with these kind of errors the underlying cause is not LecoS specific, but caused by some library mismatches installed systemwide (as, compared to Windows, QGIS on Linux is depending on python libraries installed systemwide). My hotguess would be either ogr or gdal (running 1.11.3 xenial build) as it fails querying the classes of your file. 
You could try to purge and reinstall QGIS on linux according to the official instructions from the qgis.org website.
Other than that I am unsure how else I can assist.

![screen_cea](https://user-images.githubusercontent.com/3788377/35766689-e87dbe48-08dc-11e8-8fa1-854f6e199997.png)
